version: "3.8"

services:
  nodejs:
    image: node:lts
    container_name: "cursoNodeExpMongo"
    working_dir: "/home/node/app/red_bicicletas"
    user: "node"
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
